# Set your base font size so you don't need Command++ (14-16 is comfortable for most)
font_size 16.0

# Remember the last window size when you quit
remember_window_size yes

# Remove closing confirmation window
confirm_os_window_close 0
