# 1. Reload config (Prefix + r)
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# 2. Set Prefix to Ctrl+s
set -g prefix C-s
unbind C-b
bind C-s send-prefix

set -g mouse on

# 3. Pane Navigation (Fixed the spaces)
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top  
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @catppuccin_flavor 'mocha'

# Enable tmux to pass modified key (like C-/) to nvim
set -g xterm-keys on   

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# Reduce escape time so vim receives key sequences faster
set -sg escape-time 10

# Ensure proper terminal detection
set -g default-terminal "tmux-256color"

